### ISSUE TITLE
Validation not RFC-822 compliant when mail.mime.allowutf8=false

### ISSUE THREAD

**Issue by runningonfumes** [eclipse-ee4j/mail#374]
changes made for
**_Support addressing i18n via RFC 6530/6531/6532 (6216)_** 
breaks behavior when mail.mime.allowutf8 is not true

This code in InternetAddress.java does not take into account that setting. If mail.mime.allowutf8 = false, I think the check should still be c **>=** 0177 instead of c **==** 0177

`
if (c <= 040 || c == 0177)
		throw new AddressException(
			"Local address contains control or whitespace", addr);
`

Checking an email address like péle@gmail.com used to throw an exception, now it does not, regardless of the value of mail.mime.allowutf8

**Comment by bshannon** [comment]
Yes, you're right, thanks!

**Comment by bshannon** [comment]
Unfortunately, fixing this causes the TCK to fail, so this fix will need to be deferred
until the TCK can be fixed as well.  In the mean time, the server should fail if given
an address that includes characters it doesn't support.

**Comment by trantor** [comment]
@bshannon  was this fixed in the end?

**Comment by gopuneet** [comment]
Redirected from https://github.com/jakartaee/mail-api/issues/747, this is still an issue: https://github.com/jakartaee/mail-api/blob/892fae4ac7601976ee3270040a5b16d6349ce955/api/src/main/java/jakarta/mail/internet/InternetAddress.java#L1351

Are there any plans to fix this? If so, which release is it being targeted for? Thanks

**Comment by arnt** [comment]
I don't have any plans to fix it, but my job involves making open source email software interoperate better, so… if you (@gopuneet) explain why you want this, I might be able to add something to my plans.

**Comment by arnt** [comment]
Also, as an aside, RFC 822? 2822 was published 25 years ago, why focus on 822?

**Comment by pglizniewicz** [comment]
I don't think 822 vs 2822 makes any difference for this issue. We are looking at 822 because `InternetAddress` explicitly mentions compliance with RFC 822 not 2822.

The issue is relevant, because checking if the address is valid by creating `InternetAddress` made sure, an e-mail address didn't bomb in another part of Java Mail.
